### DISCUSSION TITLE
Enable something like a Verbose mode?

### DISCUSSION THREAD

**Discussion by NJullienSweet** [oleg-shilo/wixsharp#1589] [Q&A] [answered]
Hello,
I'm trying to debug a WixSharp project of mine. When run on my PC, it runs smoothly, generates the wxs files and WiX builds them flawlessly. But when run on my GitHub Action, i ran into an error that is not even explained:

```
Wix project file has been built: D:\a\████████████████\██████████████\MyWixSharpProject\bin\Release\net472\setup.wxs

Cannot build D:\a\████████████████\██████████████\MyWixSharpProject\bin\Release\net472\setup.wxs
```

That's all I'm getting. Is there anything to toggle to get more details, like a verbose option to enable for WiX?

Thanks for you help

**Comment by smaudet** [comment]
@NJullienSweet check the project options.

**Reply by NJullienSweet** [reply]
What is this supposed to mean?

**Reply by oleg-shilo** [reply]
Yes, there is a `verbose` option. Though you will find it as a Compiler option:

```C#
Compiler.VerboseOutput = true;
```

**Reply by NJullienSweet** [reply]
Thanks indeed, found it.
Unfortunately it didn't provide much more details on why it's not compiling...

```
Wix project file has been built: D:\a\████████████████\████████████████\MyWixSharpProject\bin\Release\net472\setup.wxs
  
<- Compiling
C:\Users\runneradmin\.dotnet\tools\wix.exe build -sw1026 -sw1076 -sw1079 -sw1149  -ext "" -ext "" -ext ""  "D:\a\████████████████\████████████████\MyWixSharpProject\bin\Release\net472\setup.wxs"  -o "D:\a\████████████████\████████████████\MyWixSharpProject\bin\Release\net472\MyInstaller.exe"
->
Cannot build D:\a\████████████████\████████████████\MyWixSharpProject\bin\Release\net472\setup.wxs
```

**Comment by oleg-shilo** [comment, marked as answer]
OK, Nicolas, the problem is that WiX extensions are not installed (for some reason) on your build machine. That's why in the verbose log CLI command you have empty strings after the `-ext` switches.

This problem is not handled by WixSharp in the best way. So the dev experience is not so great. It just lets `wix.exe` report the errors but it simply swallows the empty arguments or they are swallowed by the shell.

I have just addressed it and the next release (hopefully on the weekend) will deliver the fix/improvement which will print the error saying which WiX extension is not present and how it installs it manually.

![image](https://github.com/user-attachments/assets/57b9a60f-1a5e-4651-b20e-5612f608af5d)

However, I would like to know why the extension is not present as WixSharp is expected to do it automatically for you. 
Can you check if you have .NET SDK installed on your system
```C#
wix --version
```

**Reply by NJullienSweet** [reply]
Wow thanks a lot for this fast detailed answer Oleg!
You gave me enough pointers to find by myself.
I have this job which takes care of installing WiX. Before I left the version blank so it recently automatically turned to v5 and ended up messing with the rest of the process.
```yaml
- name: Install WiX
        id: install-wix
        shell: pwsh
        continue-on-error: true
        run: |
          dotnet tool install --global wix
          wix extension add -g WixToolset.UI.wixext
          wix extension add -g WixToolset.Netfx.wixext
          wix extension add -g WixToolset.Bal.wixext
          wix extension add -g WixToolset.Util.wixext
```
So I added the "--version 4.0.3" to stop this from happening again. Following your comment, I found this topic about a bug: https://github.com/wixtoolset/issues/issues/8033 so I added the version on each extension:
```yaml
- name: Install WiX
        id: install-wix
        shell: pwsh
        continue-on-error: true
        run: |
          dotnet tool install --global wix --version 4.0.3
          wix extension add -g WixToolset.UI.wixext/4.0.3
          wix extension add -g WixToolset.Netfx.wixext/4.0.3
          wix extension add -g WixToolset.Bal.wixext/4.0.3
          wix extension add -g WixToolset.Util.wixext/4.0.3
```
And this now works as expected!
